services:
  - type: web
    name: futbol-club
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/futbol-club-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx512m"
    plan: free